version: "3.4" # x-environment is supported in version 3.4 and above
x-environment: &global_env
  DB_HOST: db
  DB_USER: postgres
  DB_PASS: postgres
  DB_NAME: AprtmentDB
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: AprtmentDB
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  realestate:
    build: ./realestate
    depends_on:
      - db
    environment:
      <<: *global_env

  server:
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      <<: *global_env

volumes:
  postgres_data:
